"""Basic API contract artifact generation from discovered routes."""

from __future__ import annotations

import re

from sydes.core.models import (
    ApiContractArtifact,
    ApiContractEvidence,
    ApiRequestContract,
    ApiResponseContract,
    ApiRouteContract,
    ApiSchema,
    ApiSchemaProperty,
    RoutesResult,
)

_PATH_PARAM_PATTERNS = [
    re.compile(r"\{([A-Za-z_]\w*)\}"),
    re.compile(r":([A-Za-z_]\w*)"),
    re.compile(r"<(?:[^:>]+:)?([A-Za-z_]\w*)>"),
]


def infer_path_params(path: str | None) -> dict[str, ApiSchemaProperty]:
    """Infer path parameter names from common path syntaxes."""
    if not isinstance(path, str) or not path:
        return {}
    names: list[str] = []
    for pattern in _PATH_PARAM_PATTERNS:
        for match in pattern.findall(path):
            if match not in names:
                names.append(match)
    return {
        name: ApiSchemaProperty(type="string", required=True, description=f"Path parameter `{name}`.")
        for name in names
    }


def _default_request_body(method: str | None) -> ApiSchema | None:
    normalized = (method or "").upper()
    if normalized in {"POST", "PUT", "PATCH"}:
        return ApiSchema(
            type="object",
            required=[],
            properties={},
            additional_properties=True,
            description="Unknown request body shape (basic skeleton).",
        )
    return None


def _default_responses(method: str | None, file: str | None, handler: str | None) -> dict[str, ApiResponseContract]:
    normalized = (method or "").upper()
    status_map = {
        "GET": ["200"],
        "POST": ["201"],
        "PUT": ["200"],
        "PATCH": ["200"],
        "DELETE": ["204"],
    }
    statuses = status_map.get(normalized, ["200"])
    responses: dict[str, ApiResponseContract] = {}
    for status in statuses:
        responses[status] = ApiResponseContract(
            status=status,
            description=f"Default {status} response skeleton.",
            body=ApiSchema(
                type="object",
                required=[],
                properties={},
                additional_properties=True,
                description="Unknown response body shape (basic skeleton).",
            ),
            confidence="low",
            evidence=[
                ApiContractEvidence(
                    kind="route_handler_reference",
                    file=file,
                    symbol=handler,
                    source="routes_discovery",
                    confidence="low",
                    notes=["Default response placeholder generated by basic contract builder."],
                )
            ],
        )
    return responses


def build_basic_api_contract_from_routes(routes_result: RoutesResult) -> ApiContractArtifact:
    """Build a first-pass API contract skeleton from discovered routes."""
    route_contracts: list[ApiRouteContract] = []
    for route in routes_result.routes:
        path_params = infer_path_params(route.path)
        request = ApiRequestContract(
            path_params=path_params,
            query_params={},
            headers={},
            body=_default_request_body(route.method),
            examples=[],
        )
        evidence = [
            ApiContractEvidence(
                kind="route_candidate",
                file=route.file,
                symbol=route.handler,
                source="routes_discovery",
                confidence="medium" if route.confidence is not None else "low",
                notes=["Contract route inferred from discovered endpoint."],
            )
        ]
        route_contracts.append(
            ApiRouteContract(
                method=route.method,
                path=route.path,
                repo=route.repo,
                service=route.service,
                handler=route.handler,
                file=route.file,
                request=request,
                responses=_default_responses(route.method, route.file, route.handler),
                evidence=evidence,
                confidence="medium" if route.confidence is not None else "low",
                notes=[
                    "Basic API contract skeleton generated from routes.",
                    "Deep request/response extraction is not enabled in C1.",
                ],
            )
        )

    return ApiContractArtifact(
        routes=route_contracts,
        notes=[
            "api_contract.json is a basic scaffold in C1.",
            "Deep contract extraction (request/response schema inference) is planned for C2.",
        ],
        confidence=0.4 if route_contracts else 0.0,
    )


def render_api_contract_json(contract: ApiContractArtifact) -> str:
    """Serialize API contract artifact as pretty JSON."""
    return contract.model_dump_json(indent=2)

